modelFileUrl: "https://github.com/api-generation/core-types/blob/main/core-types.xml"
outputDirUrl: "https://github.com/api-generation/core-types/blob/main/generated"
modelConfig:
  packageNames:
    typesPackage: "Core Types"
loader:
  loaderUrl: "http://localhost:7010"  
  configFileUrl: "https://github.com/mghaigh/common-config/blob/main/config/loaders/ea-xmi/config.yaml"
generators:
#  MkDocs:
  - generatorUrl: "http://localhost:9020"  
    configFileUrl: "https://github.com/mghaigh/common-config/blob/main/config/generators/mkdoc/config.yaml"
